### ISSUE TITLE
Philosophy on secrets creation with Helm charts

### ISSUE THREAD

**Issue by sc250024** [reactiveops/rok8s-scripts#245]
Greetings,

I'm happy to have stumbled upon this repository, and I'm extremely grateful that someone is open-sourcing something that almost everyone uses in some form (whether hand-crafted themselves, or through a SaaS provider). Standardizing this type of thing is very useful for the community.

I'm using Sops for secrets encryption, and there's one thing that confuses me about secrets creation with these scripts. Specifically, let's look at this part: https://github.com/reactiveops/rok8s-scripts/blob/master/docs/secrets.md#creating-a-new-secret. The documentation states:

> Once your editor opens up you can create a Kubernetes Secret Document. Below is an example of a kubernetes secret YAML.
> 
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: example-name
> stringData:
>   EXAMPLE_VAR: "example value"
> ```

The format of this secrets file is enforced via the following line when the secrets are deployed: https://github.com/reactiveops/rok8s-scripts/blob/master/bin/k8s-deploy-secrets#L66.

Essentially, it means that you must use the standard Kubernetes API YAML for your secrets. This approach goes against how Helm charts work. If you look at [the official repository for Helm charts](https://github.com/helm/charts), for every chart that uses the `kind: Secret` API, it's almost always a template. For example, let's take the Minio `secrets.yaml` from [here](https://github.com/helm/charts/blob/master/stable/minio/templates/secrets.yaml):

```yaml
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ .Values.accessKey | b64enc }}
  secretkey: {{ .Values.secretKey | b64enc }}
{{- if .Values.gcsgateway.enabled }}
  gcs_key.json: {{ .Values.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
{{- end }}
```

This means that control of _how_ and _where_ secrets that are encrypted via Sops are deployed is left up to the template; the only thing that happens on deployment is that the `sops` binary is called to decrypt the file, and expose those secrets as template variables for the Helm chart.

In order to use `secrets.yaml` file in the way that this repository requires, I would have to encrypt the template itself. However, this doesn't work because `sops` cannot verify that it's proper YAML. If I try to encrypt the same Minio `secrets.yaml` template above, I get the following error:

```shell
[CMD]	 ERRO[1285] Could not load tree, probably due to invalid syntax. Press a key to return to the editor, or Ctrl+C to exit.  error="Error unmarshaling input YAML: yaml: did not find expected node content"
```

It seems to me there are a couple of approaches to take here:

- Remove the requirement that Sops encrypted secrets pass a `kubeval` test, or...
- Create a Helm chart specific secrets decryption script, which would just handle decryption for a Helm chart deployments, or...
- A combination of the above, which would only do a `kubeval` test if the deployment **is not** a Helm chart deployment. Maybe an environment variable to disable `kubeval` checking in general.
- Something else which I didn't think of, and am happy to take suggestions on.

Thoughts?
