### ISSUE TITLE
k8s-deploy-and-verify silently failed

### ISSUE THREAD

**Issue by jmound** [reactiveops/rok8s-scripts#63]
relevant sections:
`circle.yml`:
```
  production:
    tag: /release-.*/
    commands:
      - ensure-kubectl
      - prepare-kubectl -f deploy/production.config
      - k8s-deploy-and-verify -f deploy/production.config
```
Output from build ([build 80 of krails-gcp-demo](https://circleci.com/gh/reactiveops/krails-gcp-demo/80)):
```
k8s-deploy-and-verify -f deploy/production.config
Reading config
Loading configuration from /home/ubuntu/krails-gcp-demo/deploy/production.config
[dockerfile]: Dockerfile
[dockertag]: krails-gcp-demo
[external_registry_base_domain]: us.gcr.io/heptagon-167420
[namespace]: production
[configmaps]: krails-production
[configmap_files]: /home/ubuntu/krails-gcp-demo/deploy/krails-production.configmap.yml
[secrets]: 
[secret_files]: 
[s3-secrets]: 
[persistent volumes]: 
[persistent_volume_files]: 
[persistent volume_claims]: 
[persistent_volume_claim_files]: 
[statefulsets]: 
[statefulset_files]: 
[services]: krails
[service_files]: /home/ubuntu/krails-gcp-demo/deploy/krails.service.yml
[endpoints]: 
[endpoint_files]: 
[ingresses]: 
[ingress_files]: 
[jobs]: 
[jobs_files]: 
[deployments]: krails-production
[deployment_files]: /home/ubuntu/krails-gcp-demo/deploy/krails-production.deployment.yml
[horizontal_pod_autoscalers]: 
[horizontal_pod_autoscaler_files]: 
[blocking jobs]: 
[blocking_jobs_files]: 
[cluster_name]: production

Deploying ConfigMaps
Applying /home/ubuntu/krails-gcp-demo/deploy/krails-production.configmap.yml
configmap "krails" created
Done deploying ConfigMaps

Deploying Secrets
Done deploying Secrets

Deploying Persistent Volumes
Done deploying Persistent Volumes

Deploying Persistent Volume Claims
Done deploying Persistent Volume Claims

Deploying StatefulSets
Done deploying StatefulSets

Deploying Services
Applying /home/ubuntu/krails-gcp-demo/deploy/krails.service.yml
service "krails" created
Done deploying Services

Deploying Endpoints
Done deploying endpoints

Deploying Ingress Resources
Done deploying Ingress Resources
Deploying Jobs
Done deploying Jobs

Deploying Blocking Jobs
Done deploying Blocking Jobs

Running Blocking Jobs

Deploying Deployments
Updating image tag from latest to 6cf3fd2a271e41dc12c0273613d0af69db1b8bae for /home/ubuntu/krails-gcp-demo/deploy/krails-production.deployment.yml
Updating /home/ubuntu/krails-gcp-demo/deploy/krails-production.deployment.yml-6cf3fd2a271e41dc12c0273613d0af69db1b8bae
deployment "krails" created
Done deploying Deployments

Deploying Horizontal Pod Autoscalers
Done deploying Horizontal Pod Autoscalers
Reading config
Loading configuration from /home/ubuntu/krails-gcp-demo/deploy/production.config
[dockerfile]: Dockerfile
[dockertag]: krails-gcp-demo
[external_registry_base_domain]: us.gcr.io/heptagon-167420
[namespace]: production
[configmaps]: krails-production
[configmap_files]: /home/ubuntu/krails-gcp-demo/deploy/krails-production.configmap.yml
[secrets]: 
[secret_files]: 
[s3-secrets]: 
[persistent volumes]: 
[persistent_volume_files]: 
[persistent volume_claims]: 
[persistent_volume_claim_files]: 
[statefulsets]: 
[statefulset_files]: 
[services]: krails
[service_files]: /home/ubuntu/krails-gcp-demo/deploy/krails.service.yml
[endpoints]: 
[endpoint_files]: 
[ingresses]: 
[ingress_files]: 
[jobs]: 
[jobs_files]: 
[deployments]: krails-production
[deployment_files]: /home/ubuntu/krails-gcp-demo/deploy/krails-production.deployment.yml
[horizontal_pod_autoscalers]: 
[horizontal_pod_autoscaler_files]: 
[blocking jobs]: 
[blocking_jobs_files]: 
[cluster_name]: production

Verifying successful deployments
Checking deployment for krails-production
Checking deployment generation
Error from server (NotFound): deployments.extensions "krails-production" not found
Error from server (NotFound): deployments.extensions "krails-production" not found
observedGeneration () should be >= generation ().
observedGeneration () is >= generation ()
Checking for updatedReplicas to equal replicas
Error from server (NotFound): deployments.extensions "krails-production" not found
Error from server (NotFound): deployments.extensions "krails-production" not found
updatedReplicas () should be == replicas ().
updatedReplicas () is == replicas ().
Checking for availableReplicas to equal replicas
Error from server (NotFound): deployments.extensions "krails-production" not found
Error from server (NotFound): deployments.extensions "krails-production" not found
availableReplicas () should be == replicas ().
availableReplicas () is == replicas ().
Deployment of krails-production was successful

DEPLOY SUCCESFUL
All objects created

```

Output from CLI:

```
$ kubectl get po
NAME                      READY     STATUS             RESTARTS   AGE
krails-2524390671-vl15s   1/2       CrashLoopBackOff   6          9m
```

**Comment by jmound** [comment]
The current version of rok8s requires that the prefix (before the first `.`  of file name matches the name of the Deployment. In this example, the file was `krails-production.deployment.yml` and the Deployment `krails`.

**Comment by jmound** [comment]
If you find that you are needing multiple deployment files, one approach that may help is to use environment variables in the deployment file.

For example:
```
...
   - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command:
          - "/cloud_sql_proxy"
          - "--dir=/cloudsql"
          - "-instances=$(DB_CONNECTION_NAME)=tcp:3306"
          - "-credential_file=/secrets/cloudsql/credentials.json"
        env:
          - name: DB_CONNECTION_NAME
            valueFrom:
              configMapKeyRef:
                name: krails
                key: db_connection_name
...
```
